In [4]:
import pandas as pd

In [5]:
# Series
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [10]:
data=[20,304,50,40]
index=['a','b','c','d']
data1=pd.Series(data,index=index)

In [17]:
# from dictionaries 
data={
    'Name':['Amruth','Akshath','Thukaram','veena'],
    'Age':[29,28,69,65],
    'City':['Bangalore','New York', 'Florida','Texas']
}
data_pd=pd.DataFrame(data)
data_pd

       Name  Age       City
0    Amruth   29  Bangalore
1   Akshath   28   New York
2  Thukaram   69    Florida
3     veena   65      Texas

In [18]:
data=pd.read_csv('datasets/data_center_hybrid.csv')
data.head()

,Year,Facility_ID,Facility_Name,Owner_Company,City,Country,Facility_Type,Estimated_Capacity_MW,PUE,Cooling_System_Type,WUE_L_per_kWh,Daily_Electricity_Usage_MWh,Daily_Water_Usage_Gallons,Surrounding_Water_Stress_Tier
0,2019,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.24,1.975,Evaporative,1.481,183.62,36362.94,Low
1,2020,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.36,1.967,Evaporative,1.459,254.34,49833.60,Low
2,2021,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.47,1.928,Evaporative,1.450,266.85,53026.35,Low
3,2022,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.59,1.897,Evaporative,1.413,199.14,39198.30,Low
4,2023,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.70,1.869,Evaporative,1.389,225.94,44366.48,Low

In [57]:
print(len(data['Country'].unique()))
df=data[data['Country']=='United States'].reset_index()
df.drop('index',axis=1,inplace=True)
df.head()

344

,Year,Facility_ID,Facility_Name,Owner_Company,City,Country,Facility_Type,Estimated_Capacity_MW,PUE,Cooling_System_Type,WUE_L_per_kWh,Daily_Electricity_Usage_MWh,Daily_Water_Usage_Gallons,Surrounding_Water_Stress_Tier
0,2019,DC-1B753A37,Silicon Valley Data Center,Fibernet,San,United States,Enterprise/Standard,4.39,1.547,Evaporative,2.340,117.57,46986.15,Medium
1,2020,DC-1B753A37,Silicon Valley Data Center,Fibernet,San,United States,Enterprise/Standard,4.50,1.536,Evaporative,2.322,151.17,60373.10,Medium
2,2021,DC-1B753A37,Silicon Valley Data Center,Fibernet,San,United States,Enterprise/Standard,4.63,1.527,Evaporative,2.289,106.69,42267.69,Medium
3,2022,DC-1B753A37,Silicon Valley Data Center,Fibernet,San,United States,Enterprise/Standard,4.75,1.501,Evaporative,2.272,138.98,55594.04,Medium
4,2023,DC-1B753A37,Silicon Valley Data Center,Fibernet,San,United States,Enterprise/Standard,4.88,1.471,Evaporative,2.210,143.34,56893.32,Medium

## loc and iloc 
- loc = row numbers and column names
- iloc - pass the indexes only

In [60]:
df.loc[0:20,['Year','Facility_Name','Country']].head()

   Year               Facility_Name        Country
0  2019  Silicon Valley Data Center  United States
1  2020  Silicon Valley Data Center  United States
2  2021  Silicon Valley Data Center  United States
3  2022  Silicon Valley Data Center  United States
4  2023  Silicon Valley Data Center  United States

In [64]:
df.iloc[0:20,[1,2,5]].head(3)

   Facility_ID               Facility_Name        Country
0  DC-1B753A37  Silicon Valley Data Center  United States
1  DC-1B753A37  Silicon Valley Data Center  United States
2  DC-1B753A37  Silicon Valley Data Center  United States

In [65]:
df.iloc[0:20,1:5].head()

   Facility_ID               Facility_Name Owner_Company City
0  DC-1B753A37  Silicon Valley Data Center      Fibernet  San
1  DC-1B753A37  Silicon Valley Data Center      Fibernet  San
2  DC-1B753A37  Silicon Valley Data Center      Fibernet  San
3  DC-1B753A37  Silicon Valley Data Center      Fibernet  San
4  DC-1B753A37  Silicon Valley Data Center      Fibernet  San

In [68]:
# accessing a specific element 
df.at[2,'City'], df.iloc[2:4,4:5]

('San',
   City
 2  San
 3  San)

In [75]:
# create new columns 
df[df['Cooling_System_Type'].isin(['Air Cooled','Liquid Cooled'])].head()

,Year,Facility_ID,Facility_Name,Owner_Company,City,Country,Facility_Type,Estimated_Capacity_MW,PUE,Cooling_System_Type,WUE_L_per_kWh,Daily_Electricity_Usage_MWh,Daily_Water_Usage_Gallons,Surrounding_Water_Stress_Tier
14,2019,DC-7AD2ECD4,1 Summer St.,Zayo Group LLC,Boston,United States,Enterprise/Standard,13.54,1.695,Air Cooled,0.073,513.42,5828.41,Medium
15,2020,DC-7AD2ECD4,1 Summer St.,Zayo Group LLC,Boston,United States,Enterprise/Standard,13.91,1.690,Air Cooled,0.072,463.03,5189.10,Medium
16,2021,DC-7AD2ECD4,1 Summer St.,Zayo Group LLC,Boston,United States,Enterprise/Standard,14.28,1.670,Air Cooled,0.070,409.21,4536.07,Medium
17,2022,DC-7AD2ECD4,1 Summer St.,Zayo Group LLC,Boston,United States,Enterprise/Standard,14.67,1.656,Air Cooled,0.069,511.50,5651.07,Medium
18,2023,DC-7AD2ECD4,1 Summer St.,Zayo Group LLC,Boston,United States,Enterprise/Standard,15.07,1.647,Air Cooled,0.067,460.41,4974.40,Medium

In [76]:
df['Average_Monthly_Water_Usage']=df['Daily_Water_Usage_Gallons']*30
df

,Year,Facility_ID,Facility_Name,Owner_Company,City,Country,Facility_Type,Estimated_Capacity_MW,PUE,Cooling_System_Type,WUE_L_per_kWh,Daily_Electricity_Usage_MWh,Daily_Water_Usage_Gallons,Surrounding_Water_Stress_Tier,Average_Monthly_Water_Usage
0,2019,DC-1B753A37,Silicon Valley Data Center,Fibernet,San,United States,Enterprise/Standard,4.39,1.547,Evaporative,2.340,117.57,46986.15,Medium,1409584.5
1,2020,DC-1B753A37,Silicon Valley Data Center,Fibernet,San,United States,Enterprise/Standard,4.50,1.536,Evaporative,2.322,151.17,60373.10,Medium,1811193.0
2,2021,DC-1B753A37,Silicon Valley Data Center,Fibernet,San,United States,Enterprise/Standard,4.63,1.527,Evaporative,2.289,106.69,42267.69,Medium,1268030.7
3,2022,DC-1B753A37,Silicon Valley Data Center,Fibernet,San,United States,Enterprise/Standard,4.75,1.501,Evaporative,2.272,138.98,55594.04,Medium,1667821.2
4,2023,DC-1B753A37,Silicon Valley Data Center,Fibernet,San,United States,Enterprise/Standard,4.88,1.471,Evaporative,2.210,143.34,56893.32,Medium,1706799.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61721,2021,DC-9C4709FE,Bozeman Data Center,Vision Net,Unknown,United States,Enterprise/Standard,1.32,1.631,Air Cooled,0.222,34.47,1240.43,Medium,37212.9
61722,2022,DC-9C4709FE,Bozeman Data Center,Vision Net,Unknown,United States,Enterprise/Standard,1.33,1.610,Air Cooled,0.221,46.67,1691.37,Medium,50741.1
61723,2023,DC-9C4709FE,Bozeman Data Center,Vision Net,Unknown,United States,Enterprise/Standard,1.33,1.603,Air Cooled,0.217,40.31,1438.82,Medium,43164.6
61724,2024,DC-9C4709FE,Bozeman Data Center,Vision Net,Unknown,United States,Enterprise/Standard,1.34,1.597,Air Cooled,0.212,48.42,1701.27,Medium,51038.1
61725,2025,DC-9C4709FE,Bozeman Data Center,Vision Net,Unknown,United States,Enterprise/Standard,1.35,1.565,Air Cooled,0.209,42.06,1480.59,Medium,44417.7

In [80]:
df.groupby('Cooling_System_Type')['Daily_Water_Usage_Gallons'].mean()

Cooling_System_Type
Air Cooled        14326.984248
Evaporative      453269.816744
Liquid Cooled     59104.537224
Name: Daily_Water_Usage_Gallons, dtype: float64